Dz
Topper-crypto/js-ps pull request #2
Opened 2024-03-17 20:48 UTC by Topper-crypto

Вечер добрый, очередная попытка

2024-03-19 09:16 UTC, GitEsense requested changes
9-sort-loops ок, но комментарии посмотрите
8-crypto и 7-converter на доработку согласно условиям

2024-03-19 09:16 UTC, GitEsense commented on 7-converter/dz1.js
> +console.log(converter(900, 'па'));
Фукнция реализована неверно, ознакомьтесь с "описанием" под домашней работой, там указано что необходимо реализовать
![image](https://github.com/Topper-crypto/js-ps/assets/101252030/151e1f6f-ead0-4f03-863b-87e280f844c7)
у Вас не все параметры реализованы
у Вас не реализована смена рубля к доллару и наоборот (направление курса как пример)
желательно реализовать через switch case или if / else if / else (но лучше подойдёт switch case)

2024-03-19 09:16 UTC, GitEsense commented on 8-crypto/dz2.js
> +console.log("Проверка пароля:", checkPassword(encrypted, password));
Это любопытно, но речь шла о реализации через массив, а не строку
Так же наименование переменной внутри функции с таким же именем - это может принести множество проблем...
Реализуйте через массив, при реализации функции checkPassword
```js
function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}
```
т.е. расшифровка пароля происходит через ту же функцию, как и шифровка

2024-03-19 09:16 UTC, GitEsense commented on 9-sort-loops/dz3.js
> +console.log("Отсортированный по убыванию массив:", sortedDescending);
Решение интересное, даже с разными вариантами сортировки, однако, количество итераций можно было бы сократить, так же передавать "number.slice()" было бы не совсем производительно, тогда уж [...number], так же лучше результирующий массив выделять уже внутри функции, тогда не будет допущено ошибки при передаче на сортировку (забыть указать slice или деструктуризацию)
но если "навести красоты" и оптимизировать итерации (в Вашем случае 16 и 12 соответственно)

Вот пример реализации:
```js
const numbers = Array.from({length: 1000}, () => Math.ceil(Math.random() * ((1000000 - 1000) + 1000) * (Math.random() > 0.5 ? 1 : -1) ))

function orderTemplate(firstNumber, secondNumber, desc = false) {
    if (!desc) {
        return firstNumber > secondNumber;
    }
    return firstNumber < secondNumber;
}

function sortArrayInAscending(array, desc = false) {
    const resultArray = [...array];
    let count = 0;
    for (let i = 0; i < resultArray.length; i++) {
        for (let j = i; j < resultArray.length; j++) {
            if (orderTemplate(resultArray[i], resultArray[j], desc)) {
                [resultArray[i], resultArray[j]] = [resultArray[j], resultArray[i]];
            }
            count++
        }
    }
    console.log(count);   //   500500 итераций
    return resultArray;
}


console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortArrayInAscending(numbers));
console.log('Отсортированный по убыванию массив:', sortArrayInAscending(numbers, true));
```

А вот Ваша реализация:
```js
function bubbleSort(arr, order) {
    let len = arr.length;
    let swapped;
    let count = 0;
    do {
        swapped = false;
        for (let i = 0; i < len - 1; i++) {
            if (order === 'asc' ? arr[i] > arr[i + 1] : arr[i] < arr[i + 1]) {
                let temp = arr[i];
                arr[i] = arr[i + 1];
                arr[i + 1] = temp;
                swapped = true;
            }
            count++;
        }
    } while (swapped);
    console.log(count);   //   965034 итераций (asc) / 993006 (desc)
    return arr;
}


let sortedAscending = bubbleSort(numbers.slice(), 'asc');
let sortedDescending = bubbleSort(numbers.slice(), 'desc');

console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortedAscending);
console.log('Отсортированный по убыванию массив:', sortedDescending);
```

2024-03-28 07:34 UTC, GitEsense approved these changes
Решения интересные, в целом всё отлично, но обратите внимание на комментарии, одно дело решить задачку и другое дело сделать функционал, который будет "универсален" и прост в использовании

2024-03-28 07:34 UTC, GitEsense commented on 7-converter/dz1.js
> +
Интересное решение, смысл был несколько другой, но реализация соответствует "требованию", однако, воспринимать сложно и в случае если курс изменится - будет сложно менять, придётся пересчитывать все "индексы"
Вот реализация для примера, где курс валют может браться "извне" и делает функцию "динамичной"

```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function converter(sum, currency, targetCurrency) {
    currency = currency.toUpperCase();
    targetCurrency = currency.toUpperCase()
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return convertSum(sum, USD, RUB) + ' руб';
                case 'EUR':
                    return convertSum(sum, USD, EUR) + ' €';
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return convertSum(sum, RUB, USD) + ' $';
                case 'EUR':
                    return convertSum(sum, RUB, EUR) + ' €';
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return convertSum(sum, EUR, RUB) + ' руб';
                case 'USD':
                    return convertSum(sum, EUR, USD) + ' $';
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }
        default: {
            console.log('Входящая валюта мне неизвестна');
            return null;
        }
    }
}


console.log(converter(100, 'RUB', 'USD'));      // 1.09 $
console.log(converter(100, 'RUB', 'EUR'));      // 0.89 €
console.log(converter(1000, 'EUR', 'USD'));     // 1229.94 $
console.log(converter(1000, 'USD', 'EUR'));     // 813.05 €
console.log(converter(1000, 'EUR', 'RUB'));     // 112330.00 руб
```

или же упрощённый вариант
```js
function converter(sum, currency, targetCurrency) {
    currency = currency.toUpperCase();
    targetCurrency = currency.toUpperCase()
    const USD = 90;
    const EUR = 100;

    switch (currency.toUpperCase()) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}

const convertResult = converter(1500, 'EUR', 'RUB');
console.log(convertResult);
```

2024-03-28 07:34 UTC, GitEsense commented on 8-crypto/dz2.js
> +    }
Эта функция не нужна, т.к. она полностью дублирует функционал функции "encryptPassword", поэтому для check можно сделать просто
```js
function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === encryptPassword(encryptedPassword);
}
```
Результат будет тот же и не за чем дублировать код, придерживаемся принципа DRY

2024-03-28 07:49 UTC, Topper-crypto commented on 8-crypto/dz2.js
> +    }
Хорошо, спасибо.

2024-03-28 07:50 UTC, merged